apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort


kind: Service 
apiVersion: v1 
metadata:
  name: hostname-service 
spec:
  type: NodePort
  selector:
    app: echo-hostname 

  ports:
    - nodePort: 30163
      port: 8080 
      targetPort: 80


[08:51] Wai Kian Ong

V#FjKkskXQK7{>569IYv